first_number = int(input("Please enter your first number "))
second_number = int(input("Please enter second number "))
third_number = int(input("Please enter third number "))
fourth_number = int(input("Please enter fourth number "))
fifth_number = int(input("Please enter fifth number "))
sixth_number = int(input("Please enter sixth number "))
seventh_number = int(input("Please enter seventh number "))
eighth_number = int(input("Please enter eighth number "))
ninth_number = int(input("Please enter ninth number "))
tenth_number = int(input("Please enter tenth number "))

difference = first_number - (second_number + third_number + fourth_number + fifth_number + sixth_number + seventh_number + eighth_number + ninth_number + tenth_number)
print (difference)