first_number = int(input("Please enter your first number "))
second_number = int(input("Please enter second number "))
third_number = int(input("Please enter third number "))
fourth_number = int(input("Please enter fourth number "))
fifth_number = int(input("Please enter fifth number "))
sixth_number = int(input("Please enter sixth number "))
seventh_number = int(input("Please enter seventh number "))
eighth_number = int(input("Please enter eighth number "))
ninth_number = int(input("Please enter ninth number "))
tenth_number = int(input("Please enter tenth number "))

number_of_odds = 0
if first_number % 2 != 0:
    number_of_odds += 1
if second_number % 2 != 0:
    number_of_odds += 1    
if third_number % 2 != 0:
    number_of_odds += 1
if fourth_number % 2 != 0:
    number_of_odds += 1
if fifth_number % 2 != 0:
    number_of_odds += 1
if sixth_number % 2 != 0:
    number_of_odds += 1
if seventh_number % 2 != 0:
    number_of_odds += 1
if eighth_number % 2 != 0:
    number_of_odds += 1
if ninth_number % 2 != 0:
    number_of_odds += 1
if tenth_number % 2 != 0:
    number_of_odds += 1
print (number_of_odds)